### ISSUE TITLE
Track users by id, not by username

### ISSUE THREAD

**Issue by cyber-sec0** [andersonkrs/malheatmap#522]
MAL does offer a way to identify the users besides by their username.

Doing so would allow the website to maintain the same data for the user, even if the user changes the username.

document.querySelector("input[name=profileMemId]").value

**Comment by andersonkrs** [comment]
That is a good point, but this selector is only available when you are logged in into your account.

MAL crawls the website as an anonymous user so it is not possible.

I have plans to create a v2 of this app that you authenticates with OAuth  and then we monitor your anime stats using the API which means you can change freely any data you want that the sync will still function.

This will take some time to get done, so I appreciate the patience and your suggestion!
