### ISSUE TITLE
Copy BBCode button not working

### ISSUE THREAD

**Issue by glenpereira** [andersonkrs/malheatmap#537]
The clipboard button used to copy the BBCode isn't working. Tested on the latest Chrome, Firefox, and Safari on a Mac.

Great work on the heatmap by the way! Who would've thought of building such a nifty app like this haha.

**Comment by andersonkrs** [comment]
Thanks for the report, I'll take a look!

**Comment by andersonkrs** [comment]
Hey just wanna let you know that it has been fixed!
