### ISSUE TITLE
Subscribing a new account returns an error 500

### ISSUE THREAD

**Issue by Iwerzhon** [andersonkrs/malheatmap#618]
I tried to subscribe my account (Ara), but it returned an error 500 instead

**Comment by HolmesSoftware** [comment]
@andersonkrs This is also affecting me. Doesn't look like its a one-case error.

**Comment by Tim-Odermatt** [comment]
Same for me...

**Comment by andersonkrs** [comment]
Hey all, that's solved, sorry for the inconvenience, Could you all test and return here for me if it worked?

**Comment by Tim-Odermatt** [comment]
now the page does not even load, due to a bad gateway error?

Bad gateway Error code 502

**Comment by andersonkrs** [comment]
Just to let you all know, mal has been blocking us from data fetching, they added a anti-bot system in front of the site, so the syncing of the data can stop working out of sudden

**Comment by bayuah** [comment]
Hey, it seem each time I see the users page today, it return error 500. Is it related issue to this one?
