### ISSUE TITLE
Getting error 500 after opening profile page

### ISSUE THREAD

**Issue by Spini11** [andersonkrs/malheatmap#768]
Hi, whenever my friend opens his profile he only gets HTTP error 500. Same thing happens no matter if he is logged in or not. Different browser didn't help.
Link to his profile: https://malheatmap.com/users/drtim

**Comment by shawbipul** [comment]
I have been facing the same issue for some time now!

**Comment by bayuah** [comment]
Me too, since 29 July 2023.

**Comment by andersonkrs** [comment]
Hey all, sorry for the inconvenience, something happened that caused an incompatibility on the existing cache. I've cleared it and it seems to be working again. Thank you for your patience.
