### ISSUE TITLE
site is broken

### ISSUE THREAD

**Issue by GDjkhp** [andersonkrs/malheatmap#875]
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/012c883e-e4ff-4348-a76f-4c64223cbe7a)

![image](https://github.com/andersonkrs/malheatmap/assets/51813377/deafcb87-8631-441d-a325-feeb53729a60)

**Comment by KanchiMoe** [comment]
Just to expand on this, and to add some more detail other than "site is broken", it seems that the scraping stopped on or after 27 January 2024.

**Comment by andersonkrs** [comment]
@KanchiMoe Thank you for explaining the issue, @GDjkhp please when opening an issue, provide the problem description, that helps a lot.

Regarding the issue, it does not seem to have stopped the scrapping

<img width="1303" alt="image" src="https://github.com/andersonkrs/malheatmap/assets/3708060/645f4dc1-f888-44f2-ac24-ce72cb327cc9">

I'll keep an eye on your profiles to see if it pauses again.

**Comment by KanchiMoe** [comment]
It does seem to have started working again (or at least updating the heatmap) within the last day or so. So the issue is resolved now for the most part.

**Comment by andersonkrs** [comment]
> It does seem to have started working again (or at least updating the heatmap) within the last day or so. So the issue is resolved now for the most part.

Well I did some changes here to possible culprits, I hope that helps, working on more reliability 🤞
