### ISSUE TITLE
Updates not tracking

### ISSUE THREAD

**Issue by Capy282** [andersonkrs/malheatmap#906]
The heatmap has been working for me fine for me after the first hiccup when first signing up a few months ago. Now however it has completely stopped working for me since Feb 6th. I tried waiting a while to see if it would be fixed, but nothing has changed so I decided to write this now.

[Heatmap Account](https://malheatmap.com/users/Capy_)
![image](https://github.com/andersonkrs/malheatmap/assets/123078259/499549f8-226c-4010-9f7a-bcefc2e224c4)

[MAL Account](https://myanimelist.net/profile/Capy_)
![image](https://github.com/andersonkrs/malheatmap/assets/123078259/12deda5a-dd2b-480e-be34-8afb6891be03)

I said this before when I first had problems, but in cases like this it would be really nice to be able to manually edit the tracker myself when it is down or not working properly. Hope this is something you will do or consider in the future.

**Comment by Capy282** [comment]
Seems it finally updated yesterday. I don't know why it's taking so long with these updates sometimes when it is supposed to be updating more frequently. It's missing my Feb 15th updates since it took so long to update again. Also the dates are wrong on the updates still even thought I have my location listed and it's even using the proper update time on the side. Do I have to be even more specific on the location? I don't get why it won't work.
![image](https://github.com/andersonkrs/malheatmap/assets/123078259/d72102d5-f19a-4984-885d-cd4aae2a9357)

**Comment by andersonkrs** [comment]
Yeah, I figured it out; it should normalize now. I removed some buggy semaphore controls; it should run updates at least once per day.

Open another issue in case you see something funky starting tomorrow on
