### ISSUE TITLE
site unreachable (again)

### ISSUE THREAD

**Issue by GDjkhp** [andersonkrs/malheatmap#912]
i noticed the site is not updating my heatmap since march? then today this happened:

![Screenshot_20240319-211557](https://github.com/andersonkrs/malheatmap/assets/51813377/58edbb5f-2a6b-48db-9b9c-47cbff8c9d70)

**Comment by andersonkrs** [comment]
It is back live, I had to take it down for some maintenance,

This week it will be normal to see the site down for couple days, I'll be messing around with the server today probably.

Thanks for the report!
