### ISSUE TITLE
stopped monitoring during march for me

### ISSUE THREAD

**Issue by GDjkhp** [andersonkrs/malheatmap#923]
btw thank you for featuring me in the readme
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/25c8e462-be35-481c-9e97-3ad8b648c8b0)
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/f8a54002-244b-45ec-930b-8fd17a14ebc2)

**Comment by andersonkrs** [comment]
Sure thanks for using this app!

Now it should be fixed, I finally figured out what was pausing synching. Now, at least once a day, the entire base user will run through sync to make sure everything is up to date.
