### ISSUE TITLE
it stopped tracking again

### ISSUE THREAD

**Issue by GDjkhp** [andersonkrs/malheatmap#950]
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/621e8b01-90f9-41fc-83fd-08223175c2fb)
![image](https://github.com/andersonkrs/malheatmap/assets/51813377/5aad5ce1-d8b7-410e-a965-d3beed564204)

**Comment by Shark-93** [comment]
For me the page itself loads / works; I have registered last week and I had activity, but now it's saying I do not have any activity in 2024. You titled the issue "again", is this a common problem you are facing?

**Comment by andersonkrs** [comment]
@Shark-93 what's your username please?

@GDjkhp I'm sorry for the service stopping, it should be back now for good. I've been struggling to find a setup where MAL does not block the service.

**Comment by Shark-93** [comment]
Thank you for your work Anderson, the page is working again now.
I will [buy you a coffee](https://buymeacoffee.com/andersonkrs) to help you ☕ Take care!

**Comment by andersonkrs** [comment]
> Thank you for your work Anderson, the page is working again now. I will [buy you a coffee](https://buymeacoffee.com/andersonkrs) to help you ☕ Take care!

Appreciate that!
